# Generated by Django 5.0.7 on 2024-12-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stripe_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=255, unique=True)),
                ('stripe_product_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('photo', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='listings',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='synced_to_stripe',
            field=models.BooleanField(default=False),
        ),
    ]
